export const Types = {
    GET_WOODS: 'GET_WOODS',
    GET_WOOD: 'GET_WOOD',
    ADD_WOOD: 'ADD_WOOD',
    MOVE_WOOD: 'MOVE_WOOD',
    REMOVE_WOOD: 'REMOVE_WOOD',
    UPDATE_WOOD: 'UPDATE_WOOD',
    ADD_WOOD_FILTER: 'ADD_WOOD_FILTER',
}
