export const Types = {
  GET_PALLETS: 'GET_PALLETS',
  GET_PALLET: 'GET_PALLET',
  GET_PALLET_LOGS: 'GET_PALLET_LOGS',
  GET_PALLET_WOOD: 'GET_PALLET_WOOD',
  ADD_PALLET: 'ADD_PALLET',
  REMOVE_PALLET: 'REMOVE_PALLET',
  UPDATE_PALLET: 'UPDATE_PALLET',
}
