export const Types = {
    GET_PALLETS: 'GET_PALLETS',
    GET_PALLET: 'GET_PALLET',
    UPDATE_SQUARE_METER: 'UPDATE_SQUARE_METER',
    GET_PALLET_STATS: 'GET_PALLET_STATS',
    GET_PALLET_LOGS: 'GET_PALLET_LOGS',
    GET_PALLET_SUB_LOGS: 'GET_PALLET_SUB_LOGS',
    GET_PALLET_WOOD: 'GET_PALLET_WOOD',
    ADD_PALLET: 'ADD_PALLET',
    ADD_PALLET_FILTER: 'ADD_PALLET_FILTER',
    REMOVE_PALLET: 'REMOVE_PALLET',
    UPDATE_PALLET: 'UPDATE_PALLET',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
