export const Types = {
  GET_COMMON_DATA: 'GET_COMMON_DATA',
  GET_PENDING_ACTIONS: 'GET_PENDING_ACTIONS',
  CHANGE_LEAVE_STATUS: 'CHANGE_LEAVE_STATUS',
  GET_WHO_IS_OUT: 'GET_WHO_IS_OUT',
  GET_MY_TEAM: 'GET_MY_TEAM'
}
