export const Types = {
    GET_SPECIES: 'GET_SPECIES',
    GET_SPECIE: 'GET_SPECIE',
    ADD_SPECIE: 'ADD_SPECIE',
    ADD_SPECIE_FILTER: 'ADD_SPECIE_FILTER',
    REMOVE_SPECIE: 'REMOVE_SPECIE',
    UPDATE_SPECIE: 'UPDATE_SPECIE',
}
