export const Types = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  NEW_USER: 'NEW_USER',
  SET_USER_DATA: 'SET_USER_DATA',
  GET_USER_DETAIL: 'GET_USER_DETAIL',
  DELETE_USER: 'DELETE_USER',
  GET_USER_ROLES: 'GET_USER_ROLES',
  ADD_USER_ROLE: 'ADD_USER_ROLE',
  SET_ROLE_DATA: 'SET_ROLE_DATA',
  GET_ACTIVE_USER_ROLES: 'GET_ACTIVE_USER_ROLES',
  GET_DASHBOARD_DATA: 'GET_DASHBOARD_DATA',
  GET_TIME: 'GET_TIME',
}
